name: test

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        dotnet build -c Release NewLife.Core/NewLife.Core.csproj
        dotnet build -c Release NewLife.Security/NewLife.Security.csproj
    #- name: Redis Server
    #  uses: supercharge/redis-github-action@1.4.0
    #- name: Test
    #  run: |
    #    dotnet test -c Release XUnitTest.Core/XUnitTest.Core.csproj
