name: test

on:
  push:
    branches: [ master ]
    paths:
        - 'NewLife.Core/**'
  pull_request:
    branches: [ master ]
    paths:
        - 'NewLife.Core/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Build
      run: |
        dotnet build -c Release NewLife.Core\NewLife.Core.csproj
        dotnet build -c Release NewLife.Security\NewLife.Security.csproj
